Run finetune on olivia
Reaches CPU Evaluation Callback but backward pass fails:

/cluster/home/sinoa/venv/lib/python3.12/site-packages/torch/utils/checkpoint.py:86: UserWarning: None of the inputs have requ
ires_grad=True. Gradients will be None
  warnings.warn(
Traceback (most recent call last):
  File "/cluster/home/sinoa/scripts/finetune_olivia.py", line 326, in <module>
    fine_tune_model(
  File "/cluster/home/sinoa/scripts/finetune_olivia.py", line 290, in fine_tune_model
    trainer.train()
  File "/cluster/home/sinoa/venv/lib/python3.12/site-packages/transformers/trainer.py", line 2052, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/cluster/home/sinoa/venv/lib/python3.12/site-packages/transformers/trainer.py", line 2388, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/home/sinoa/venv/lib/python3.12/site-packages/transformers/trainer.py", line 3518, in training_step
    self.accelerator.backward(loss, **kwargs)
  File "/cluster/home/sinoa/venv/lib/python3.12/site-packages/accelerate/accelerator.py", line 2734, in backward
    loss.backward(**kwargs)
  File "/cluster/home/sinoa/venv/lib/python3.12/site-packages/torch/_tensor.py", line 648, in backward
    torch.autograd.backward(
  File "/cluster/home/sinoa/venv/lib/python3.12/site-packages/torch/autograd/__init__.py", line 353, in backward
    _engine_run_backward(
  File "/cluster/home/sinoa/venv/lib/python3.12/site-packages/torch/autograd/graph.py", line 824, in _engine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn